import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import api from '../service/api'
import { useState, useEffect } from 'react'


const Home: NextPage = () => {
  const [person, setPerson] = useState<any[]>([])
  const [finnish, setFinnish] = useState<boolean>(false)

  useEffect(() => {
    async function fetchApi() {
      const response: any = await api.get('people')
      setPerson(response.data.results)

      for (let i: number = 2; i <= response.data.count / 10; i++) {
        const result = await api.get(`people/?page=${i}`)
        setPerson(person => person += result.data.results)
      }
      setFinnish(true)
    }
    fetchApi()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <table>
          <tr>
            <th>Company</th>
            <th>Contact</th>
          </tr>
          {!finnish && <p>Loading...</p>}
          {finnish && person && person.map((item: any, index: number) => (
            <tr key={index}>
              <td>{item.name}</td>
              <td>{item.birth_year}</td>
            </tr>
          ))}
        </table>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          Marcílio Júnior
        </a>
      </footer> */}
    </div >
  )
}

export default Home
